quarkus:
  application:
    name: weather-service
  http:
    port: 8080

  rest-client:
    openweather-api:
      url: https://api.openweathermap.org
      connect-timeout: 5000
      read-timeout: 5000

    weather-api:
      url: https://api.weatherapi.com
      connect-timeout: 5000
      read-timeout: 5000

  log:
    level: INFO
    category:
      "com.julian.weather":
        level: DEBUG

  swagger-ui:
    always-include: true

  jackson:
    fail-on-unknown-properties: false

openweather:
  api-key: ${OPENWEATHER_API_KEY}
  client:
    units: metric
    language: es

weatherapi:
  api-key: ${WEATHER_API_KEY}
  client:
    language: es

"%test":
  quarkus:
    rest-client:
      weather-api:
        url: http://localhost:9999
      openweather-api:
        url: http://localhost:9999
    log:
      level: WARN

  weatherapi:
    api-key: test-api-key
    client:
      language: es

  openweather:
    api-key: test-api-key
    client:
      units: metric
      language: es