quarkus.application.name=hexagonal-application
quarkus.http.port=8080

# --- Logging ---
quarkus.log.level=INFO
quarkus.log.category."com.weatherapp".level=DEBUG

# --- OpenWeatherMap reactive REST client ---
quarkus.rest-client."openweathermap-api".url=https://api.openweathermap.org
quarkus.rest-client."openweathermap-api".scope=jakarta.inject.Singleton
quarkus.rest-client."openweathermap-api".connect-timeout=5000
quarkus.rest-client."openweathermap-api".read-timeout=5000

# API Key: Utilizar variables de entorno o reemplazar por la api key correspondiente
openweathermap.api.key=${OPENWEATHERMAP_API_KEY:01010101}
